services:
  model-api:
    image: simple-model-inference-api:cu126
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        EXTRA: gpu
    container_name: simple-model-inference-api-container
    ports:
      - "8000:8000"
    environment:
      - INFERENCE_DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/app/.venv/lib/python3.12/site-packages/tensorrt_libs:$LD_LIBRARY_PATH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
